name: Setup Rust Environment
description: Install system dependencies, Rust toolchain, and setup caching

inputs:
  components:
    description: Rust toolchain components to install
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev pkg-config
      shell: bash

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.components }}

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
