name: Setup Rust Environment
description: Install system dependencies, Rust toolchain, setup caching, and optionally install cargo-nextest

inputs:
  components:
    description: Rust toolchain components to install
    required: false
    default: ''
  nextest:
    description: Whether to install cargo-nextest
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev pkg-config
      shell: bash

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.components }}

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: ci-global
        save-if: true

    - name: Install cargo-nextest
      if: inputs.nextest == 'true'
      uses: taiki-e/install-action@nextest

    - name: Install sccache
      uses: taiki-e/install-action@v2
      with:
        tool: sccache

    - name: Configure sccache
      shell: bash
      run: |
        if [[ -n "${ACTIONS_CACHE_URL:-}" && -n "${ACTIONS_RUNTIME_TOKEN:-}" ]]; then
          export RUSTC_WRAPPER=sccache
          export SCCACHE_GHA_ENABLED=true
          export SCCACHE_CACHE_SIZE=500M
          echo "RUSTC_WRAPPER=$RUSTC_WRAPPER" >> "$GITHUB_ENV"
          echo "SCCACHE_GHA_ENABLED=$SCCACHE_GHA_ENABLED" >> "$GITHUB_ENV"
          echo "SCCACHE_CACHE_SIZE=$SCCACHE_CACHE_SIZE" >> "$GITHUB_ENV"
          sccache --start-server || true
        else
          echo "ACTIONS_CACHE_URL missing; running without sccache"
          echo "RUSTC_WRAPPER=" >> "$GITHUB_ENV"
          echo "SCCACHE_GHA_ENABLED=" >> "$GITHUB_ENV"
          echo "SCCACHE_CACHE_SIZE=" >> "$GITHUB_ENV"
        fi
